import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import cn from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-white px-52")}>
        {/* <header className="bg-white w-full h-16 rounded-b-xl flex justify-between">

        </header> */}
        {children}
        {/* <footer></footer> */}
      </body>
    </html>
  );
}
